#   [category,question,answer,fake1,fake2,fake3]

knowledge = [
['mysql',
 'What is a join?',
 'Join bring data from two tables together',
 'Join takes 2 bool conditions requiring both',
 'Join bring data from two columns together',
 'Join groups columns together'],

['mysql',
 'What is the difference between a Where and a Having',
 'Having filters on groups, and where filters on rows',
 'Where filters on groups, and having filters on rows',
 'Where and Having are the same thing',
 'Having can be used without groups, Where requires groups'],

['mysql',
 'What is the correct order of SELECT,WHERE,GROUP BY,HAVING',
 'SELECT * WHERE * GROUP BY * HAVING *',
 'SELECT * GROUP BY * WHERE * HAVING *',
 'SELECT * WHERE * HAVING * GROUP BY *',
 'GROUP BY * HAVING * SELECT * WHERE *'],

['mysql',
 'How do you do selections to eliminate any duplicate records in a column?',
 'DISTINCT',
 'UNIQUE',
 'EACH',
 'EXPLICIT'],

['python',
 'Which of the following is not a reserved word in Python',
 'iterate',
 'None',
 'break',
 'except'],

['python',
 'A code block is defined by:',
 'Indentation and whitespace',
 'A set of curly brackets',
 'The end of one semicolin to the next',
 'A set of angle brackets'],

['python',
 'Can you have an empty code block?',
 'No, however the pass keyword can be used to make the code block do nothing',
 'Yes, an empty code block will be ignored',
 'Yes, an empty code block is the same as return None',
 'No, however the Nothing keyword can be used to make the code block do nothing'],

['python',
 'The difference between a list and a tuple is:',
 'A list is mutable a tuple is not',
 'A list is ordered a tuple is not',
 'A list is indexed a tuple is not',
 'A list can have duplicates a tuple can not'],

['pandas',
 'What is the difference between a dataframe and a series?',
 'A dataframe has multiple columns, series has one',
 'A series has multiple columns, dataframe has one',
 'A dataframe has multiple rows, series has one',
 'A series has multiple rows, dataframe has one'],

['pandas',
 'pd.Series([1,2], index= ["a","b","c"])',
 'Syntax Error',
 'Index Error',
 'Value Error',
 'None of these'],

['pandas',
 'What will be the minimum number of arguments require to pass in pandas series?',
 'None of these',
 '3',
 '4',
 '2'],

['pandas',
 'Amongst which of the following is / are used to analyze the data in pandas',
 'Both of these',
 'Dataframe',
 'Series',
 'None of these'],

['pandas',
 's =pd.Series([1,2,3,4,5],index= ["a","b","c","d","e"])\nprint(s["f"])',
 'ValueError',
 'IndexError',
 'KeyError',
 'None of these']
]
